# Kafka
kafka.bootstrap.servers=kafka:9092
kafka.topic=test-topic
kafka.topic.order=dwd_order_detail
kafka.group.id.dagGmv=flink-day-gmv-group
kafka.starting.offsets=earliest

# Flink
flink.parallelism=1
flink.checkpoint.interval=5000
flink.checkpoint.storage=file:///tmp/flink-checkpoints/daily-gmv

# Doris
doris.fenodes=doris-fe:8030
doris.table.identifier.dailyGmv=linyu.ads_realtime_gvm
doris.username=root
doris.password=Linyu@123

# Doris Stream Load
# 测试环境如果不从 checkpoint/savepoint 恢复，而是重新提交一个全新作业，需要换一个新的 label prefix。
doris.sink.label.prefix=flink_daily_gmv_20260605_2
doris.sink.format=json
doris.sink.read.json.by.line=true
doris.sink.buffer.flush.max.rows=10000
doris.sink.buffer.flush.interval.ms=1000

# MySQL
mysql.url=jdbc:mysql://localhost:3306/test_db
mysql.username=root
mysql.password=123456
